version: '3.7'

services:

  committee_client:
    container_name: committeeClient
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/DockerfileCommittee
    image: committee_client
    hostname: CommitteeClient
    expose:
      - 20002
      - 20012
    networks:
      - elections_net

networks:
  elections_net:
    external: true