version: '3.7'

# Ports convention:
#      2XXYZ
#
# XX - State number
# Y  - Server index in cluster
# Z  - 0 for REST server service
#      1 for gRPC client service
#      2 for gRPC server service

services:

  elections_server_ca_0:
    container_name: serverCA
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-CA
    environment:
      - DOCKER_ELECTIONS_STATE=CA
      - DOCKER_ELECTIONS_REST0=20000
      - DOCKER_ELECTIONS_REST1=20003
      - DOCKER_ELECTIONS_REST2=20006
    ports:
      - 20000:20000
      - 20001:20001
      - 20002:20002
      - 20003:20003
      - 20004:20004
      - 20005:20005
      - 20006:20006
      - 20007:20007
      - 20008:20008
      - 5005:5005
    networks:
      - elections_net

  elections_server_tx_0:
    container_name: serverTX
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-TX
    environment:
      - DOCKER_ELECTIONS_STATE=TX
      - DOCKER_ELECTIONS_REST0=20100
      - DOCKER_ELECTIONS_REST1=20103
      - DOCKER_ELECTIONS_REST2=20106
    ports:
      - 20100:20100
      - 20101:20101
      - 20102:20102
      - 20103:20103
      - 20104:20104
      - 20105:20105
      - 20106:20106
      - 20107:20107
      - 20108:20108
    networks:
      - elections_net

  elections_server_ks_0:
    container_name: serverKS
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-KS
    environment:
      - DOCKER_ELECTIONS_STATE=KS
      - DOCKER_ELECTIONS_REST0=20020
      - DOCKER_ELECTIONS_REST1=20023
      - DOCKER_ELECTIONS_REST2=20026
    ports:
      - 20020:20020
      - 20021:20021
      - 20022:20022
      - 20023:20023
      - 20024:20024
      - 20025:20025
      - 20026:20026
      - 20027:20027
      - 20028:20028
    networks:
      - elections_net

  elections_server_wy_0:
    container_name: serverWY
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-WY
    environment:
      - DOCKER_ELECTIONS_STATE=WY
      - DOCKER_ELECTIONS_REST0=20120
      - DOCKER_ELECTIONS_REST1=20123
      - DOCKER_ELECTIONS_REST2=20126
    ports:
      - 20120:20120
      - 20121:20121
      - 20122:20122
      - 20123:20123
      - 20124:20124
      - 20125:20125
      - 20126:20126
      - 20127:20127
      - 20128:20128
    networks:
      - elections_net

#  elections_server_ca_1:
#    container_name: serverCA1
#    build:
#      context: .
#      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
#    image: elections_server
#    hostname: ElectionsServer-CA-1
#    environment:
#      - DOCKER_ELECTIONS_STATE=CA
#      - DOCKER_ELECTIONS_HOSTNAME=serverCA1
#      - DOCKER_ELECTIONS_REST_PORT=20010
#      - DOCKER_ELETIONS_RMI_PORT=20012
#    ports:
#      - 20010:20010
#      - 20011:20011
#      - 20012:20012
#      - 5015:5005
#    networks:
#      - elections_net
#
#  elections_server_ca_2:
#    container_name: serverCA2
#    build:
#      context: .
#      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
#    image: elections_server
#    hostname: ElectionsServer-CA-2
#    environment:
#      - DOCKER_ELECTIONS_STATE=CA
#      - DOCKER_ELECTIONS_HOSTNAME=serverCA2
#      - DOCKER_ELECTIONS_REST_PORT=20020
#      - DOCKER_ELETIONS_RMI_PORT=20022
#    ports:
#      - 20020:20020
#      - 20021:20021
#      - 20022:20022
#      - 5025:5005
#    networks:
#      - elections_net
#
#  elections_server_tx_0:
#    container_name: serverTX0
#    build:
#      context: .
#      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
#    image: elections_server
#    hostname: ElectionsServer-TX-0
#    environment:
#      - DOCKER_ELECTIONS_STATE=TX
#      - DOCKER_ELECTIONS_HOSTNAME=serverTX0
#      - DOCKER_ELECTIONS_REST_PORT=20100
#      - DOCKER_ELETIONS_RMI_PORT=20102
#    ports:
#      - 20100:20100
#      - 20101:20101
#      - 20102:20102
#      - 5105:5105
#    networks:
#      - elections_net
#
#  elections_server_tx_1:
#    container_name: serverTX1
#    build:
#      context: .
#      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
#    image: elections_server
#    hostname: ElectionsServer-TX-1
#    environment:
#      - DOCKER_ELECTIONS_STATE=TX
#      - DOCKER_ELECTIONS_HOSTNAME=serverTX1
#      - DOCKER_ELECTIONS_REST_PORT=20110
#      - DOCKER_ELETIONS_RMI_PORT=20112
#    ports:
#      - 20110:20110
#      - 20111:20111
#      - 20112:20112
#    networks:
#      - elections_net
#
#  elections_server_tx_2:
#    container_name: serverTX2
#    build:
#      context: .
#      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
#    image: elections_server
#    hostname: ElectionsServer-TX-2
#    environment:
#      - DOCKER_ELECTIONS_STATE=TX
#      - DOCKER_ELECTIONS_HOSTNAME=serverTX2
#      - DOCKER_ELECTIONS_REST_PORT=20120
#      - DOCKER_ELETIONS_RMI_PORT=20122
#    ports:
#      - 20120:20120
#      - 20121:20121
#      - 20122:20122
#    networks:
#      - elections_net


networks:
  elections_net:
    external: true
