version: '3.7'

# Ports convention:
#      2XXYZ
#
# XX - State number
# Y  - Server index in cluster
# Z  - 0 for REST server service
#      1 for gRPC client service
#      2 for gRPC server service

services:

  elections_server_ca_0:
    container_name: serverCA0
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-CA-0
    environment:
      - DOCKER_ELECTIONS_STATE=CA
      - DOCKER_ELECTIONS_HOSTNAME=serverCA0
      - DOCKER_ELECTIONS_REST_PORT=20000
      - DOCKER_ELETIONS_RMI_PORT=20002
    ports:
      - 20000:20000
      - 20001:20001
      - 20002:20002
      - 5005:5005
    networks:
      - elections_net

  elections_server_ca_1:
    container_name: serverCA1
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-CA-1
    environment:
      - DOCKER_ELECTIONS_STATE=CA
      - DOCKER_ELECTIONS_HOSTNAME=serverCA1
      - DOCKER_ELECTIONS_REST_PORT=20010
      - DOCKER_ELETIONS_RMI_PORT=20012
    ports:
      - 20010:20010
      - 20011:20011
      - 20012:20012
      - 5015:5005
    networks:
      - elections_net

  elections_server_ca_2:
    container_name: serverCA2
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-CA-2
    environment:
      - DOCKER_ELECTIONS_STATE=CA
      - DOCKER_ELECTIONS_HOSTNAME=serverCA2
      - DOCKER_ELECTIONS_REST_PORT=20020
      - DOCKER_ELETIONS_RMI_PORT=20022
    ports:
      - 20020:20020
      - 20021:20021
      - 20022:20022
      - 5025:5005
    networks:
      - elections_net

  elections_server_tx_0:
    container_name: serverTX0
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-TX-0
    environment:
      - DOCKER_ELECTIONS_STATE=TX
      - DOCKER_ELECTIONS_HOSTNAME=serverTX0
      - DOCKER_ELECTIONS_REST_PORT=20100
      - DOCKER_ELETIONS_RMI_PORT=20102
    ports:
      - 20100:20100
      - 20101:20101
      - 20102:20102
      - 5105:5105
    networks:
      - elections_net

  elections_server_tx_1:
    container_name: serverTX1
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-TX-1
    environment:
      - DOCKER_ELECTIONS_STATE=TX
      - DOCKER_ELECTIONS_HOSTNAME=serverTX1
      - DOCKER_ELECTIONS_REST_PORT=20110
      - DOCKER_ELETIONS_RMI_PORT=20112
    ports:
      - 20110:20110
      - 20111:20111
      - 20112:20112
    networks:
      - elections_net

  elections_server_tx_2:
    container_name: serverTX2
    build:
      context: .
      dockerfile: ./ElectionsController/ElectionsServer/Dockerfile
    image: elections_server
    hostname: ElectionsServer-TX-2
    environment:
      - DOCKER_ELECTIONS_STATE=TX
      - DOCKER_ELECTIONS_HOSTNAME=serverTX2
      - DOCKER_ELECTIONS_REST_PORT=20120
      - DOCKER_ELETIONS_RMI_PORT=20122
    ports:
      - 20120:20120
      - 20121:20121
      - 20122:20122
    networks:
      - elections_net


networks:
  elections_net:
    external: true
